version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: fulani_quiz_postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-fulani_quiz}
      POSTGRES_USER: ${DB_USER:-fulani}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-fulani_password}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: fulani_quiz_backend
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: ["sh", "/app/entrypoint.sh"]

volumes:
  pgdata:
